data:
  main_data_dir: "data/core_docs"
  benchmark_data_path: "data/benchmark/benchmark_data_multilabel.json"
  benchmark_results_path: "data/benchmark/benchmark_report_final.csv"
scraper:
  start_url: "https://v4fire.github.io/Core/modules.html"
  base_domain: "v4fire.github.io/Core"
  docs_dir: "data/core_docs"
  concurrency_limit: 20
  min_context_length: 50
model:
  model_id: "qwen3:8b"
  llm_api_url: ${LLM_API_URL}
  retrieval_top_k: 5
  collection_name: "docs_final"
